# The character(s) that Bash Multi Command will look for to split a single chat message into multiple ones.
separator: ';'
# The permission needed to use multiple commands.
permission: 'bashmulticommand.use'
# The language to use. You can make your own language file and use that.
language: en_US
# Whether or not to autoupdate
autoupdate: true